services:
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: demo_app_backend
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #     minio:
  #       condition: service_healthy
  #   environment:
  #     POSTGRES_PORT: ${POSTGRES_PORT}
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_HOST: db
  #     POSTGRES_DB: ${POSTGRES_DB}
  #     S3_ACCESS_KEY: ${S3_ACCESS_KEY}
  #     S3_SECRET_KEY: ${S3_SECRET_KEY}
  #     S3_HOST: minio
  #     S3_PORT: ${S3_PORT}
  #     S3_BUCKET: ${S3_BUCKET}
  #     S3_SECURE: ${S3_SECURE}
  #     S3_TYPE: ${S3_TYPE}
  #   ports:
  #     - "8000:8000"
  #   restart: unless-stopped

  db:
    image: postgres:18-alpine
    container_name: demo_app_postgres
    env_file:
      - .env.docker
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d demo_app"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    container_name: demo_app_minio
    command: server /data --console-address ":9001"
    env_file:
      - .env.docker
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_KEY}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
    name: demo_app_postgres_data
  minio_data:
    name: demo_app_minio_data
